In [203]:
%load_ext numpy_html 

The numpy_html extension is already loaded. To reload it, use:
  %reload_ext numpy_html


In [204]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

In [205]:
# EXERCISE 1 QUESTION 1

In [206]:
# LIST OF 15 1'S
list = [1] * 15
print(list)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [207]:
# LIST OF 15 7'S
list = [7] * 15
print(list)

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]


In [208]:
# LIST OF NUMBERS BETWEEN 100 - 150
for x in range(100, 150):
    print(x)

100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149


In [209]:
# LIST OF NUMBERS BETWEEN 0 - 100 THAT ARE EVEN
for x in range(0, 100):
    if x % 2 == 0:
        print(x)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


In [210]:
# LIST OF YEARS BETWEEN 1950 - 2020 THAT ARE DIVISIBLE BY 4
for x in range(1950, 2020):
    if x % 4 == 0:
        print(x)

1952
1956
1960
1964
1968
1972
1976
1980
1984
1988
1992
1996
2000
2004
2008
2012
2016


In [211]:
import numpy as np

In [212]:
# EXERCISE 1 QUESTION 2

In [213]:
# LIST OF 15 ZEROS
zeros = np.zeros(15)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [214]:
# LIST OF 15 ONES
ones = np.ones(15)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [215]:
# LIST OF 15 SEVENS
sevens = np.ones(15).astype(int)*7
sevens

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [216]:
# LIST OF NUMBERS FROM 100 - 150
list = np.arange(100, 150)
list

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [217]:
# LIST OF NUMBERS FROM 1900 - 2021
list = np.arange(1900, 2021)
list

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [218]:
#  LIST OF EVEN NUMBERS BETWEEN 0 - 100
even_list = np.arange(0, 100, 2)
even_list

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [219]:
# LIST OF ALL YEARS BETWEEN 1950 - 2020 DIVISIBLE BY 4
list = np.arange(1950, 2020)
filtered = list[list % 4 == 0]
filtered

array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016])

In [220]:
# Numpy is easier than Python as it requires less punctuation and therefore is less likely to have punctuation errors!

In [221]:
# EXERCISE 1 QUESTION 3

In [222]:
# FINDING LARGEST VALUE
data = (5, 16, 9, 2, 19, 18, 11, 7)
list = np.array(data)
max_value = list.argmax()
max_value

4

In [223]:
# CREATING A MATRIX
matrix = np.arange(1, 50)
matrix = matrix.reshape(7, 7)
matrix

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [224]:
# CREATING MATRIX IN PYTHON
matrix = [[ 1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19, 20, 21],
         [22, 23, 24, 25, 26, 27, 28],
         [29, 30, 31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40, 41, 42],
         [43, 44, 45, 46, 47, 48, 49]]

for row in matrix:
    print(row)

[1, 2, 3, 4, 5, 6, 7]
[8, 9, 10, 11, 12, 13, 14]
[15, 16, 17, 18, 19, 20, 21]
[22, 23, 24, 25, 26, 27, 28]
[29, 30, 31, 32, 33, 34, 35]
[36, 37, 38, 39, 40, 41, 42]
[43, 44, 45, 46, 47, 48, 49]


In [225]:
# CREATING A MATRIX NUMBER BETWEEN 0 - 5, 8 X 8
data = np.random.randint(0, 6, 64)
data = data.reshape(8, 8)
data

array([[3, 3, 5, 5, 3, 2, 0, 4],
       [5, 5, 0, 3, 0, 1, 3, 4],
       [1, 1, 2, 1, 3, 4, 3, 3],
       [2, 3, 2, 3, 3, 0, 4, 4],
       [2, 2, 0, 3, 2, 5, 5, 5],
       [0, 2, 1, 4, 3, 0, 3, 4],
       [5, 1, 3, 1, 4, 2, 4, 0],
       [1, 0, 5, 1, 4, 0, 5, 3]])

In [226]:
# CREATING A MATRIX, STANDARD NORMAL DISTRIBUTION, 8 X 8
data = np.random.randn(3)
data = np.random.randn(8, 8)
data

array([[-1.4087832 , -0.03780494,  0.33704537,  0.33925102, -1.29410758,
         0.56465878,  0.06517872, -0.13034239],
       [ 0.58057966,  1.26617356,  0.77654332, -1.44503974,  0.94606392,
         1.33366603,  0.36122819, -0.27911441],
       [-0.12444411, -0.03346476, -0.55969314, -0.88311644, -0.45564498,
         0.62605648,  0.42920067,  0.69963196],
       [-0.9895698 , -2.28869508,  1.54981097, -1.206708  ,  0.52790368,
         1.97821025,  0.17392252, -1.09497321],
       [-1.79293416,  0.68444532,  1.60254464, -0.4476695 , -0.12930571,
        -2.78896067, -0.70919831,  1.40439383],
       [-2.77258594,  1.34540528,  1.29028336,  0.01159553, -1.37003105,
        -0.20283312,  1.62213321, -0.54690361],
       [-0.93036177, -1.74137394,  1.43991854,  0.99747117, -0.1684477 ,
         1.35830101, -0.36979262, -0.18594997],
       [ 2.37011337, -1.44337697,  1.88904136, -0.23000966,  0.85234568,
         0.50972118, -0.67873114, -0.57796674]])

In [227]:
# EXERCISE 1 QUESTION 4

In [228]:
# LINEARLY SPACED ARRAY, RANDOMLY GENERATED
data = np.linspace(0, 1, 10)
data

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [229]:
# LINEARLY SPACED ARRAY, RANDOMLY GENERATED 10 X 10
data = np.linspace(0, 5, 100)
data = data.reshape(10, 10)
data

array([[0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545],
       [0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596],
       [1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646],
       [1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697],
       [2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747],
       [2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798],
       [3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848],
       [3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737374,
        3.78787879, 3.83838384, 3.88888889, 3.93939394, 3.98989899],
       [4.04040404, 4.09090909, 4.14141414, 4.19191919, 4.24242424,
        4.29292929, 4.34343434, 4.39393939, 4.44444444, 4.49494949],
       [4.54545455, 4.5959596 , 4.64646465, 4.6969697 , 4.74747475,
        4.7979798 , 4.84848485, 4.8989899 , 4.94949495, 5.        ]])

In [230]:
# EXEERCISE 1 QUESTION 5

In [231]:
# CREATING A MATRIX FROM IMAGE
data = np.array([23, 34, 54, 31, 75, 33, 56, 78, 65, 97, 41, 32, 11, 39, 51])
data = data.reshape(3, 5)
data

array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

In [232]:
# CREATING A MATRIX FROM IMAGE
data = np.arange(128, 256)
data = data.reshape(8, 16)
data

array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

In [233]:
# CREATING A MATRIX FROM IMAGE
data = np.arange(0.05, 5.05, 0.05)
new = data.reshape(10, 10)
new

array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

In [234]:
# EXERCISE 1 QUESTION 6

In [235]:
# USING A MATRIX
dataset = np.arange(1, 37).reshape(6, 6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [236]:
# SLICING PART A
dataset = np.arange(1, 37).reshape(6, 6)
slice = dataset[3:, 2:]
slice

array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

In [237]:
# SLICING PART B
dataset = np.arange(1, 37).reshape(6, 6)
slice = dataset[:4, 3]
slice

array([ 4, 10, 16, 22])

In [238]:
# SLICING PART C
dataset = np.arange(1, 37).reshape(6, 6)
slice = dataset[2]
slice

array([13, 14, 15, 16, 17, 18])

In [239]:
# SLICING PART D
dataset = np.arange(1, 37).reshape(6, 6)
slice = dataset[3:]
slice

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [240]:
# EXERCISE 1 QUESTION 7

In [241]:
# ALTERING PROVIDED DATA
dataset = np.arange(1, 50).reshape(7, 7)
dataset

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [242]:
# ADDING
dataset = np.arange(1, 50).reshape(7, 7)
dataset = dataset + 50
dataset

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [243]:
# SUM
dataset = np.arange(1, 50).reshape(7, 7)
sum = np.sum(dataset)
sum

1225

In [244]:
# SUM ONLY ODD
dataset = np.arange(1, 50).reshape(7, 7)
odd = dataset[dataset % 2 != 0]
sum = np.sum(odd)
sum

625

In [245]:
# STANDARD DEVIATION
dataset = np.arange(1, 50).reshape(7, 7)
std_deviation = np.std(dataset)
std_deviation

14.142135623730951

In [246]:
# SUM BY ROW 
dataset = np.arange(1, 50).reshape(7, 7)
sum = np.sum(dataset, axis=1)
sum

array([ 28,  77, 126, 175, 224, 273, 322])

In [247]:
# SUM BY COLUMN
dataset = np.arange(1, 50).reshape(7, 7)
sum = np.sum(dataset, axis=0)
sum

array([154, 161, 168, 175, 182, 189, 196])